### ISSUE TITLE
Bluetooth cannot be enabled anymore - btuart initialization timed out

### ISSUE THREAD

**Issue by jaharkema** [RPi-Distro/pi-bluetooth#23] opened 2021-05-19 23:50 UTC
Since upgrading from 0.1.15 to 0.1.16, I cannot get Bluetooth to work anymore. I am not sure about the exact details, but pi-bluetooth is the only package that was recently updated. Sadly, I cannot downgrade, because 0.1.15 is no longer in [the repository](http://archive.raspberrypi.org/debian/dists/buster/main/binary-armhf/Packages).

In /var/log/apt/history.log:

```
Start-Date: 2021-05-19  02:35:08
Commandline: /usr/bin/unattended-upgrade
Upgrade: pi-bluetooth:armhf (0.1.15, 0.1.16)
End-Date: 2021-05-19  02:36:16
```

hciuart status

```
$ sudo systemctl status hciuart.service
● hciuart.service - Configure Bluetooth Modems connected by UART
Loaded: loaded (/lib/systemd/system/hciuart.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Thu 2021-05-20 01:19:36 CEST; 19min ago
Process: 18328 ExecStart=/usr/bin/btuart (code=exited, status=1/FAILURE)
May 20 01:19:06 hassio systemd[1]: Starting Configure Bluetooth Modems connected by UART...
May 20 01:19:36 hassio btuart[18328]: Initialization timed out.
May 20 01:19:36 hassio btuart[18328]: bcm43xx_init
May 20 01:19:36 hassio systemd[1]: hciuart.service: Control process exited, code=exited, status=1/FAILURE
May 20 01:19:36 hassio systemd[1]: hciuart.service: Failed with result 'exit-code'.
May 20 01:19:36 hassio systemd[1]: Failed to start Configure Bluetooth Modems connected by UART.
```

journalctl -xe after restarting hciuart

```
May 20 01:16:18 hassio btuart[17931]: Initialization timed out.
May 20 01:16:18 hassio btuart[17931]: bcm43xx_init
May 20 01:16:18 hassio systemd[1]: hciuart.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- An ExecStart= process belonging to unit hciuart.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 1.
May 20 01:16:18 hassio systemd[1]: hciuart.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit hciuart.service has entered the 'failed' state with result 'exit-code'.
May 20 01:16:18 hassio systemd[1]: Failed to start Configure Bluetooth Modems connected by UART.
-- Subject: A start job for unit hciuart.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit hciuart.service has finished with a failure.
--
-- The job identifier is 90699 and the job result is failed.
```

Manually trying to connect a device:

```
$ sudo hciattach /dev/ttyAMA0 bcm43xx 921600 noflow
bcm43xx_init
Initialization timed out.
```

**Comment by jaharkema** [comment] 2021-05-20 00:00
I realized I forgot my system specs:

```
$ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : c03112
Serial          : 10000000dd80e0d8
Model           : Raspberry Pi 4 Model B Rev 1.2
```

**Comment by va1entin** [comment] 2021-05-20 08:21
Hi @jaharkema I'm facing problems as well since the update to 0.1.16 and submitted a PR with changes that made it work again. It is a WIP and I'm no bluetooth expert; just in case it might help you: #22

**Comment by pelwell** [comment] 2021-05-20 08:42
Duplicate of #22 - let's continue the discussion there.

**Closed as completed by pelwell** 2021-05-20 08:42 UTC
